from typing import Sequence, Mapping

from . import timeline

def create_ontology(
    parent_timelines: str,
    parent_map: Mapping[str, str],
    recorded_date_codes: Sequence[str],
    output_filename: str,
) -> None: ...

class OntologyReader:
    def __init__(self, filename: str): ...
    def get_subwords(self, word: int) -> Sequence[int]: ...
    def get_parents(self, subword: int) -> Sequence[int]: ...
    def get_all_parents(self, subword: int) -> Sequence[int]: ...
    def get_children(self, subword: int) -> Sequence[int]: ...
    def get_words_for_subword(self, subword: int) -> Sequence[int]: ...
    def get_words_for_subword_term(self, term: str) -> Sequence[int]: ...
    def get_recorded_date_codes(self) -> Sequence[int]: ...
    def get_dictionary(self) -> timeline.TermDictionary: ...
